id: P009385
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14674
  title: འབྲི་གུང་གསོ་རིག་གཅེས་བསྡུས།
  author: ''
  volumes:
    63e4f7705e7e4675a1170e6f9dfb117e:
      image_group_id: I1KG15758
      title: ''
      volume_number: 1
      total_pages: 334
      base_file: v001.txt
    2bf13ae6544747579180700acef2191f:
      image_group_id: I1KG15759
      title: ''
      volume_number: 2
      total_pages: 382
      base_file: v002.txt
